// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB25R6CHM_UGRGV3K8jPg1IHBLru8pdT2I',
    appId: '1:726011282042:web:61a2a8d7c5a950950031c3',
    messagingSenderId: '726011282042',
    projectId: 'mimetic-campus-405713',
    authDomain: 'mimetic-campus-405713.firebaseapp.com',
    storageBucket: 'mimetic-campus-405713.appspot.com',
    measurementId: 'G-W8YBNK2757',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQqWYqv2MevVheJFFLjhHWfZtPtkLH_dY',
    appId: '1:726011282042:android:0e98b85aa04685910031c3',
    messagingSenderId: '726011282042',
    projectId: 'mimetic-campus-405713',
    storageBucket: 'mimetic-campus-405713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF8VqCHJeAmkQPhxSSi3oHNS_qBuolC3c',
    appId: '1:726011282042:ios:5a045f8ed027e9860031c3',
    messagingSenderId: '726011282042',
    projectId: 'mimetic-campus-405713',
    storageBucket: 'mimetic-campus-405713.appspot.com',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF8VqCHJeAmkQPhxSSi3oHNS_qBuolC3c',
    appId: '1:726011282042:ios:5a045f8ed027e9860031c3',
    messagingSenderId: '726011282042',
    projectId: 'mimetic-campus-405713',
    storageBucket: 'mimetic-campus-405713.appspot.com',
    iosBundleId: 'com.example.wallpaper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB25R6CHM_UGRGV3K8jPg1IHBLru8pdT2I',
    appId: '1:726011282042:web:c415970ac6fe10a90031c3',
    messagingSenderId: '726011282042',
    projectId: 'mimetic-campus-405713',
    authDomain: 'mimetic-campus-405713.firebaseapp.com',
    storageBucket: 'mimetic-campus-405713.appspot.com',
    measurementId: 'G-W79R2CNG6N',
  );
}
